
export default class CommonConstants {

  static readonly HOME_TITLE = '推荐';

  static readonly WOMAN_TITLE = '女装';

  static readonly MAN_TITLE = '男装';

  static readonly SPORT_TITLE = '运动';

  static readonly TEC_TITLE = '电脑办公';

  static readonly OTHER_TITLE = '其他';

  static readonly USER_TITLE = '个人中心';

  static readonly SUB_TITLE = '订阅';

  static readonly SHOP_TITLE = '购物车';

  static readonly HOME_TAB_INDEX = 0;

  static readonly WOMAN_TAB_INDEX = 10;

  static readonly MAN_TAB_INDEX = 11;

  static readonly SPORT_TAB_INDEX = 12;

  static readonly TEC_TAB_INDEX = 13;

  static readonly SUB_TAB_INDEX = 2;

  static readonly USER_TAB_INDEX = 2;

  static readonly SHOP_TAB_INDEX = 1;

  static readonly FULL_PARENT = '100%';

  static readonly OTHER_PARENT = '95%';

  static readonly COMMON_SPACE = 12;

  static readonly Category_TITLE1 = '精选分类';

  static readonly Category_TITLE2 = '上装';

  static readonly Category_TITLE3 = '下装';

  static readonly COLOR_TITLE = '颜色';

  static readonly SIZE_TITLE = '尺码';

  static readonly ORDER_SIZE_TITLE = '数量';

  static readonly SET_LIST_WIDTH = '42%';

  static readonly BUTTON_WIDTH = '90%';

  static readonly MY_ORDERS = '我的订单';
}